<?php


/**
 * Implements hook_install().
 */
function hook_install() {
  $rest = \Drupal::configFactory()->getEditable('rest.settings');

  $resources = $rest->get('resources');

  $resources['entity:bat_event'] = array(
    'PATCH' => array(
      'supported_formats' => array(
        'hal_json',
        'json',
      ),
      'supported_auth' => array(
        'cookie',
      ),
    ),
  );

  $rest->set('resources', $resources)->save(TRUE);
}
