<?php


/**
 * Implements hook_install().
 */
function hook_install() {
  $rest = \Drupal::configFactory()->getEditable('rest.settings');

  $resources = $rest->get('resources');

  $resources['entity:bat_event'] = [
    'PATCH' => [
      'supported_formats' => [
        'hal_json',
        'json',
      ],
      'supported_auth' => [
        'cookie',
      ],
    ],
  ];

  $rest->set('resources', $resources)->save(TRUE);
}
